### ISSUE TITLE
Any Documentation about the usage of Boundary/Component/Endpoint?

### ISSUE THREAD

**Issue by zerg000000** [duct-framework/duct#46]
Although the code of this project is quite clean and easy-to-read, I think documentation of this project is quite minimum. I have a bit confuse of the Concept of the Boundary/Component/Endpoint in duct context and cannot find any example/documentation to get it clear. It would be nice to have some example/doc like http://www.luminusweb.net/docs does.

**Comment by weavejester** [comment]
I do need to add more documentation, but could you explain what you find confusing in more detail?

**Comment by zerg000000** [comment]
I don't know what should be placed into `boundary`. According to code generated from `gen/boundary`, the boundary should be some additional behaviours for one component.

```
(defprotocol DBQuery
  (some-methods-useful-for-? [this]))

(extend-protocol DBQuery
  ns.component.jdbc.JDBC
  (some-methods-useful-for-? [this] ...))
```

It seems like a good place for adding general useful functions related to the component, but don't seems like a good place for business logic, as business logic always have multi dependencies. e.g. when handling a application form submission, the system might need to validate form data via a few web service components before saving data via jdbc component. If business logic is not the piece of code to be placed under `boundary`, what should be placed in `boundary` instead?

My current understanding

`boundary` - code using `component`
`component` - code for creating stateful objects living in `system`
`endpoint` - routes consumed by `HandlerComponent`

**Comment by adairdavid** [comment]
As far as I understand...
Boundaries are for explicitly defining the point at which data enters or leaves your system. You can think of them as an interface you can code against where your system shouldn't care about the implementation detail.
For example, a boundary could be a AccountsDatabase. You would define a protocol for this interface which would define the contract of the boundary such as (get-account [this]).
Then, you can extend (implement) this protocol on different types/components in your system. So you might extend the type HikariCP to implement this boundary protocol so that you can fetch data from a jdbc connection, or you can extend say the Atom type so that tests/dev can use a fake in-memory "database".
Really, a boundary is an abstraction around some external resource.
Business logic would be in regular namespaces that would be coordinated through your endpoints. So your endpoint may receive several component dependencies and then orchestrate your business logic around those dependencies.



On Tue, Oct 18, 2016 at 2:21 AM -0600, "albert lai" <notifications@github.com> wrote:












I don't know what should be placed into boundary. According to code generated from gen/boundary, the boundary should be some additional behaviours for one component.

(defprotocol DBQuery
  (some-methods-useful-for-? [this]))

(extend-protocol DBQuery
  ns.component.jdbc.JDBC
  (some-methods-useful-for-? [this] ...))




It seems like a good place for adding general useful functions related to the component, but don't seems like a good place for business logic, as business logic always have multi dependencies. e.g. when handling a application form submission, the system might need to validate form data via a few web service components before saving data via jdbc component. If business logic is not the piece of code to be placed under boundary, what should be placed in boundary instead?



My current understanding



boundary - code using component

component - code for creating stateful objects living in system

endpoint - routes consumed by HandlerComponent

**Comment by weavejester** [comment]
@adairdavid is exactly right. I'll also put up an wiki entry that goes into boundaries in more detail, and provides some examples, as this is clearly a weak link in the documentation.

Another link that might be useful is my blog post on [How I use Component](https://www.booleanknot.com/blog/2016/01/24/how-i-use-component.html).

**Comment by weavejester** [comment]
I've added a wiki entry on [Boundaries](https://github.com/duct-framework/duct/wiki/Boundaries).

**Comment by zerg000000** [comment]
Thanks guys! I have better understand now. Clearly, `boundary` should be a minimum interface for business logic to interact with `component` related to data movement, so we could reduce the coupling between business logic and the `component`. The `boundary` should not be too low level, to leak too much details to the business logic. e.g. the implementation of `component` ( jdbcTemplate, Datasource...), the protocols used by different parts of business domain. Therefore, business logic should live in its own namespace.

Where should be the transaction boundary? extend the example in blog post a bit
 
e.g.

```{clojure}
(defn notify-customer-of-order [db mailer customer-name order-number]
  (let [customer                      (get-customer-by-name db customer-name)
        order                            (get-order-by-number db order-number)
        {:keys [status time]}   (send-email mailer (new-order-email customer order))]
     (save-order (assoc order :mail-status status :mail-time time))
``` 

`get-customer-by-name`, `get-order-by-number`, `save-order` are in separate transactions, read/write might not be consistent. e.g. `get-order-by-number` results might not be consistent with the result of `get-customer-by-name`. So, we need to add some transaction code like

```{clojure}
(defn notify-customer-of-order [db mailer customer-name order-number]
  ; just pesudo code
  (with-tx db
    (let [customer                      (get-customer-by-name db customer-name)
          order                            (get-order-by-number db order-number)
          {:keys [status time]}   (send-email mailer (new-order-email customer order))]
       (save-email-result {:mail-status status :mail-time time :customer customer-name :orderno order-number}))
```

In this case, `notify-customer-of-order` should be part of the `boundary` or not?
or in other words, is `boundary` equal to transaction boundary?

**Comment by weavejester** [comment]
First, don't think of boundaries as having anything directly to do with business logic. A boundary is concerned with separating what's *internal* to the application with what's *external* to the application. Business logic is an orthogonal concept to this.

Regarding transactions, in general they belong on the external side of the boundary, because they're an implementation detail of the database. For example:

```clojure
;; Bad
(defprotocol AccountsDatabase
  (with-tx* [db func])
  (credit [db to amount])
  (debit [db from amount]))

;; Good
(defprotocol AccountsDatabase
  (transfer [db from to amount]))
```

Transactions are useful, but they also complect operations together and degrade performance. Ideally transactions should be used sparingly.

**Comment by kendagriff** [comment]
Just wanted to chime in quickly.

I think this is probably **_the_** thing that deserves the best documentation. I've now experimented with half a dozen different patterns for separating boundary concerns, and ultimately settled on something really similar to this.

**Comment by zerg000000** [comment]
Thanks! Now, I have a stronger sense about the `boundary` in duct. I will experiment around this pattern to see if it could solve real-life problems cleaner than before.

I have no more comment about the usage of component/boundary/endpoint. Please close the issue if not further discussion about this topic.

Thanks guys!

**Comment by MokkeMeguru** [comment]
sry to dig up the previous party.
I wanna think of some examples using transactions e.g. remittance.

In the previous case, we transfer X dollars from the sender to the receiver.

```
1. subtract X dollars from Sender's account 
2. add X dollars from Receiver's account 
```

It's very simple to understand the process.

However, some real banks need to be payed handling charge. And also, reward points too.

```
1. subtract X dollers from Sender's account
2. add X dollers into Receiver's account
3. subtract Y dollers from Sender's account
4. add Z reward points into Sender's account
5. others process ... 
```

It is too complex process but they need transactions.

So that, I want to know how to deal with these complex transaction process in the clojure's boundary. (I agree to decouple the transaction from the business logic.)

Thanks for your library !
